scripts

diff --git a/scripts/cluster-serving/cluster-serving-start b/scripts/cluster-serving/cluster-serving-start
--- a/scripts/cluster-serving/cluster-serving-start
+++ b/scripts/cluster-serving/cluster-serving-start
@@ -101,12 +101,28 @@ if [ -z "${SPARK_REDIS_JAR}" ]; then
     SPARK_REDIS_JAR=spark-redis-2.4.0-jar-with-dependencies.jar
 fi
 
-if [ -z "${1// }" ]; then
+while [ "$1" != "" ]; do
+    case $1 in
+        -e | --engine )         shift
+                                backend=$1
+                                ;;
+        -c | --config_path )    shift
+                                config_path=$1
+                                ;;
+        -h | --help )           usage
+                                exit
+                                ;;
+        * )                     usage
+                                exit 1
+    esac
+    shift
+done
+if [ -z "${backend// }" ]; then
     echo "Using default setting, starting Cluster Serving with Flink backend"
-    ${FLINK_HOME}/bin/flink run -c com.intel.analytics.zoo.serving.ClusterServing -p 1 zoo.jar
+    ${FLINK_HOME}/bin/flink run -c com.intel.analytics.zoo.serving.ClusterServing -p 1 zoo.jar -c $config_path
 else
-  if [ $1 != "spark" ]; then
-    echo "You provided invalid parameter when start serving, supported parameter is spark, your is "$1
+  if [ $backend != "spark" ]; then
+    echo "You provided invalid parameter when start serving, supported parameter is spark, your is "$backend
     exit 1
   fi
   # try to start tensorboard
