Cluster Serving scripts clean up and single job flink JobId control (#2608)

diff --git a/scripts/cluster-serving/cluster-serving-start b/scripts/cluster-serving/cluster-serving-start
--- a/scripts/cluster-serving/cluster-serving-start
+++ b/scripts/cluster-serving/cluster-serving-start
@@ -80,11 +80,7 @@ else
     ${REDIS_HOME}/src/redis-cli config set maxclients 10000
 fi
 
-# try to start tensorboard
-#if [[ ! -e "TensorboardEventLogs" ]]; then
-#    mkdir TensorboardEventLogs
-#fi
-#tensorboard --logdir ./TensorboardEventLogs --port 6006 --host 0.0.0.0 &
+
 
 # if jar paths are not set, try to use them in current directory
 if [ -z "${ZOO_JAR}" ]; then
@@ -105,14 +101,37 @@ if [ -z "${SPARK_REDIS_JAR}" ]; then
     SPARK_REDIS_JAR=spark-redis-2.4.0-jar-with-dependencies.jar
 fi
 
-if [ -z "${1// }" ]; then
+while [ "$1" != "" ]; do
+    case $1 in
+        -e | --engine )         shift
+                                backend=$1
+                                ;;
+        -c | --config_path )    shift
+                                config_path=$1
+                                ;;
+        -h | --help )           usage
+                                exit
+                                ;;
+        * )                     usage
+                                exit 1
+    esac
+    shift
+done
+if [ -z "${backend// }" ]; then
     echo "Using default setting, starting Cluster Serving with Flink backend"
-    ${FLINK_HOME}/bin/flink run -c com.intel.analytics.zoo.serving.ClusterServing -p 1 zoo.jar
+    ${FLINK_HOME}/bin/flink run -c com.intel.analytics.zoo.serving.ClusterServing -p 1 zoo.jar -c $config_path
 else
-  if [ $1 != "spark" ]; then
-    echo "You provided invalid parameter when start serving, supported parameter is spark, your is "$1
+  if [ $backend != "spark" ]; then
+    echo "You provided invalid parameter when start serving, supported parameter is spark, your is "$backend
     exit 1
   fi
+  # try to start tensorboard
+  if [[ ! -e "TensorboardEventLogs" ]]; then
+      mkdir TensorboardEventLogs
+  fi
+  tensorboard --logdir ./TensorboardEventLogs --port 6006 --host 0.0.0.0 &
+
+
     if [ "${params_performance_mode}" == "ON" ] && [ "${spark_master}" == "local[*]" ]; then
      echo -e "\033[36mPerformance mode is ON, Start standalone cluster... \033[0m"
      if [ -f "cluster-with-numactl.sh" ]; then
@@ -135,7 +154,7 @@ else
       echo -e "\033[31m${PARAMS[1]}, use local[*] instead \033[0m"
      fi
     fi
-    ${SPARK_HOME}/bin/spark-submit --master ${spark_master} --driver-memory ${spark_driver_memory} --executor-memory ${spark_executor_memory} --num-executors ${spark_num_executors} --executor-cores ${spark_executor_cores} --total-executor-cores ${spark_total_executor_cores} --jars ${SPARK_REDIS_JAR},${BIGDL_JAR} --class com.intel.analytics.zoo.serving.SparkStreamingClusterServing ${ZOO_JAR} >> cluster-serving.log
+    ${SPARK_HOME}/bin/spark-submit --master ${spark_master} --driver-memory ${spark_driver_memory} --executor-memory ${spark_executor_memory} --num-executors ${spark_num_executors} --executor-cores ${spark_executor_cores} --total-executor-cores ${spark_total_executor_cores} --jars ${SPARK_REDIS_JAR},${BIGDL_JAR} --class com.intel.analytics.zoo.serving.SparkStreamingClusterServing ${ZOO_JAR}
 fi
 
 
